name: CI
on:
  workflow_dispatch: # For GUI manual trigger
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install Angular cli'
        run: npm install -g @angular/cli

      - name: 'Install NPM packages'
        run: npm ci

      - name: 'Lint'
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install Jest'
        run: npm install -g jest

      - name: 'Install NPM packages'
        run: npm ci

      - name: 'Test'
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install Angular cli'
        run: npm install -g @angular/cli

      - name: 'Install NPM packages'
        run: npm ci

      - name: 'Build'
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    name: 🚀Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set environment deploy token
        run: |
            if [ ${{ github.ref }} = 'refs/heads/main' ]
            then
              export AZURE_STATIC_WEB_APP_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ISLAND_07B76E503 }}
            else
              export AZURE_STATIC_WEB_APP_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FOREST_03E024503 }}
            fi
            echo "token = $AZURE_STATIC_WEB_APP_API_TOKEN"

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ISLAND_07B76E503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/demo"
